[level]
tests = [
  { in = [
    "B",
    "O",
    "O",
    "T",
    "S",
    "E",
    "Q",
    "U",
    "E",
    "N",
    "C",
    "E",
  ], out = [
    "B",
    "O",
    "O",
    "T",
    "S",
    "E",
    "Q",
    "U",
    "E",
    "N",
    "C",
    "E",
  ] },
]

[goals]
size = 6
speed = 6
